### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by vors** [KirkMunro/LanguagePx#2]
I noticed that you have dll check-ed in.
Are you planning to open the source code for this dll as well?

**Comment by KirkMunro** [comment]
It is checked in.  I place all binary module code in a separate branch called "assembly".  That way I can separate PowerShell from C# and avoid confusing those who would otherwise be confused.

**Comment by vors** [comment]
Oh, I see.

> That way I can separate PowerShell from C# and avoid confusing those who would otherwise be confused
> ![image](https://cloud.githubusercontent.com/assets/816680/10256418/08a040d4-6906-11e5-94b5-35b546bbf7f1.png)

Sure, no confusion :D

**Comment by KirkMunro** [comment]
Yeah, I know, it's not standard according to how developers create Github projects, but I've found it works better for IT Pros this way, plus it keeps the module easily downloadable at all times if someone wants the latest without a bunch of stuff they might not care about.
